### ISSUE TITLE
Custom tags aren't actually used

### ISSUE THREAD

**Issue by wensimehrp** [GukkyGukz/TW-Trains-Set#4]
`custom_tags.txt` provides a set of configurable tags to reduce the chance of making mistakes and the time cost of synchronizing the language files. In TWTS there are custom tags defined but they are not used in the language file.

The way to fix this is quite easy. Say, `TITLE` is defined, to use it, just type `{TITLE}` in the language file and nmlc will auto replace it with the defined value when compiling (something like using the C preprocessor where you use `#define foo bar`)

Thus, some strings could be simplified to something like this:
```
// original
STR_NAME    :TW Trains Set <some version>
// fixed
STR_NAME    :{TITLE} {VERSION}
```

There are more advanced usage of custom tags, for example I defined `DATE` in CNSPS to show the compile date.

**Comment by GukkyGukz** [comment]
fixed it just now! thanks as i havent realized 😁
